<?php

$node = null;

function drup_al_theme($existing, $type, $theme, $path) {
  $module_path =  drupal_get_path('module', 'drup_al');
  return [
    'post_list' => [
      'path' => $module_path . '/templates',
      'variables' => ['posts' => NULL],
    ],
  ];
}

function drup_al_node_presave(Drupal\node\NodeInterface $node) {
  
  switch ($node->bundle()) {
    case 'post':
      post_presave($node);
    break;
  }

}

function post_presave(Drupal\node\NodeInterface $node) {
  if($node->bundle() == 'post') {
    $node->set('field_post_slug',
      \Drupal::service('pathauto.alias_cleaner')
        ->cleanString($node->get('title')->value)
    );   
  }
}