<?php

use Drupal\Core\PhpStorage\PhpStorageFactory;
use Drupal\Core\Cache\Cache;
use Symfony\Component\HttpFoundation\RedirectResponse;

$node = null;

function drup_al_theme($existing, $type, $theme, $path) {
  $module_path =  drupal_get_path('module', 'drup_al');
  return [
    'main_index' => [
      'path' => $module_path . '/templates/index',
    ],
    'error_404' => [
      'path' => $module_path . '/templates/error',
    ],
    'post_list' => [
      'path' => $module_path . '/templates/post',
      'variables' => ['posts' => NULL],
    ],
    'post_view' => [
      'path' => $module_path . '/templates/post',
      'variables' => ['post' => false],
    ],
  ];
}

function drup_al_user_login($account) {
  if($account->hasRole('system_admin')) {
    //redirect to admin page
    $response = new RedirectResponse('/admin', '301');
    $response->send();
    exit(0);
  }
}

function drup_al_node_presave(Drupal\node\NodeInterface $node) {
  
  switch ($node->bundle()) {
    case 'post':
      post_presave($node);
    break;
  }
  
  drup_al_clear_cache();
}

function drup_al_node_delete(Drupal\node\NodeInterface $node) {
  //last case: delete all Twig cache
  drup_al_clear_cache();
}

function post_presave(Drupal\node\NodeInterface $node) {
  if($node->bundle() == 'post') {
    $node->set('field_post_slug',
      \Drupal::service('pathauto.alias_cleaner')
        ->cleanString($node->get('title')->value)
    );
  }
}

function drup_al_clear_cache() {
  //last case: delete all Twig cache after post create/update 
  $module_handler = \Drupal::moduleHandler();
  $module_handler->invokeAll('cache_flush');
  // Cache::getBins()['page']->deleteAll();
  foreach (Cache::getBins() as $service_id => $cache_backend) {
   $cache_backend->deleteAll();
  }
}